name: Release

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:
    inputs:
      overwrite:
        description: "Overwrite output even if it doesn't seem outdated? Boolean. Default: false"
        required: true
        default: 'false'


jobs:
  release:
    runs-on: "ubuntu-latest"

    steps:
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "current"
        title: "Current release"
        files: |
          *.tar.gz
          *.MD

