name: Release

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:
    inputs:
      logLevel:
        default: 'warning'

jobs:
  release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "current"
            title: "Current release"
            files: |
              *.tar.gz
              *.MD

